FROM elceef/dnstwist:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3-pil python3-selenium chromium-driver && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
